### ISSUE TITLE
Sign-out button redirects to non-existent URL

### ISSUE THREAD

**Issue by bytech-ca** [eclectic-bytech/webcourses-ngx-v4#57]
When signing out from [the webcourses area](http://homestead.test/webcourses/user/webcourses/), the post-logout redirect goes to `https://wngx.localundefined/`. It should go to the home page (on the Vagrant env, that's http://homestead.test, though obviously we want that to be a generic solution that knows where the home page is on that specific instance.)

**Comment by mrshychip** [comment]
🟢 This issue is now pending complete.

I resolved this issue by creating a logout controller php file in app/Https/controllers and also updated the web file to reflect the new controller functions in /routes/web.php (New code in the bottom of the file).

The new code tells Laurval to sign you out and then take you back to the sign in page.

**Comment by bytech-ca** [comment]
When I run the code, I get a "missing {" error. :(

**Comment by mrshychip** [comment]
⚠️ There is a potential breakpoint in this issue, testing is ongoing.

**Comment by bytech-ca** [comment]
I believe the link isn't working due to the dashboard's original path being `/dashboard`. This was changed to `/user/dashboard/`, quite likely in the wrong place.

Let's solve this by finding where we can change the system's dashboard path to `/user/dashboard` so that the entire system knows about it. Not by hacking paths in the template linking to `/dashboard`.

**Comment by bytech-ca** [comment]
Resolved this one without a logout controller which was quite a complicated solution 😅 A fix was implemented while working on issues #36 and #66.
